# Generated by Django 5.1.4 on 2024-12-31 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_medecin_specialite'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='specialite',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
